---
replicaCount: 1

image:
  tag: "0.1.1"

fullnameOverride: "consumer-controlplane"

## EDC endpoints exposed by the control-plane
edc:
  endpoints:
    ## Default api exposing health checks etc
    default:
      # -- The network port, which the "default" api is going to be exposed by the container, pod and service
      port: "8080"
      # -- The path mapping the "default" api is going to be exposed at
      path: /api
    ## Data management API
    data:
      # -- The network port, which the "data" management api is going to be exposed by the container, pod and service
      port: "8181"
      # -- The path mapping the "data" management api is going to be exposed at
      path: /data
    ## Validation API
    validation:
      # -- The network port, which the "validation" api is going to be exposed by the container, pod and service
      port: "8182"
      # -- The path mapping the "validation" api is going to be exposed at
      path: /validation
    ## Control API
    control:
      # -- The network port, which the "control" api is going to be exposed by the container, pod and service
      port: "9999"
      # -- The path mapping the "control" api is going to be exposed at
      path: /api/controlplane/control
    ## IDS endpoints
    ids:
      # -- The network port, which the "ids" multipart api is going to be exposed by the container, pod and service
      port: "8282"
      # -- The path mapping the "ids" multipart api is going to be exposed at
      path: /BPNL00000003CML1/api/v1/ids
    ## Prometheus endpoint
    metrics:
      # -- The network port, which the prometheus metrics are going to be exposed by the container, pod and service
      port: "9090"
      # -- The path mapping the prometheus metrics are going to be exposed at
      path: /metrics

## Ingress declaration to expose the network service.
ingresses:
  ## Public / Internet facing Ingress
  - enabled: true
    # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
    hostname: consumer-controlplane.dev.demo.ftcpro.co
    # -- Additional ingress annotations to add
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # -- EDC endpoints exposed by this ingress resource
    endpoints:
      - data
    # -- Defines the [ingress class](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)  to use
    className: "nginx"
    # -- Enables TLS on the ingress resource
    tls: 
      enabled: true
    ## Adds [cert-manager](https://cert-manager.io/docs/) annotations to the ingress resource
    certManager:
      clusterIssuer: letsencrypt-prod

resources:
  limits:
    cpu: 2
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 100Mi

configuration:
  # -- EDC configuration.properties configuring aspects of the [eclipse-dataspaceconnector](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector)
  properties: |-
    edc.api.auth.key=<path:traceability-foss/data/dev/edc/controlplane#edc.api.control.auth.apikey.value>
    web.http.default.port=8080
    web.http.default.path=/api
    web.http.data.port=8181
    web.http.data.path=/data
    web.http.validation.port=8182
    web.http.validation.path=/validation
    web.http.control.port=9999
    web.http.control.path=/api/controlplane/control
    web.http.ids.port=8282
    web.http.ids.path=/BPNL00000003CML1/api/v1/ids
    edc.api.control.auth.apikey.key=X-Api-Key
    # Postgresql related configuration
    edc.datasource.asset.name=asset
    edc.datasource.asset.url=jdbc:postgresql://ftcpro-postgresql-primary.postgres:5432/edc_2?currentSchema=consumer
    edc.datasource.asset.user=edc
    edc.datasource.asset.password=<path:traceability-foss/data/dev/database#password>
    edc.datasource.contractdefinition.name=contractdefinition
    edc.datasource.contractdefinition.url=jdbc:postgresql://ftcpro-postgresql-primary.postgres:5432/edc_2?currentSchema=consumer
    edc.datasource.contractdefinition.user=edc
    edc.datasource.contractdefinition.password=<path:traceability-foss/data/dev/database#password>
    edc.datasource.contractnegotiation.name=contractnegotiation
    edc.datasource.contractnegotiation.url=jdbc:postgresql://ftcpro-postgresql-primary.postgres:5432/edc_2?currentSchema=consumer
    edc.datasource.contractnegotiation.user=edc
    edc.datasource.contractnegotiation.password=<path:traceability-foss/data/dev/database#password>
    edc.datasource.policy.name=policy
    edc.datasource.policy.url=jdbc:postgresql://ftcpro-postgresql-primary.postgres:5432/edc_2?currentSchema=consumer
    edc.datasource.policy.user=edc
    edc.datasource.policy.password=<path:traceability-foss/data/dev/database#password>
    edc.datasource.transferprocess.name=transferprocess
    edc.datasource.transferprocess.url=jdbc:postgresql://ftcpro-postgresql-primary.postgres:5432/edc_2?currentSchema=consumer
    edc.datasource.transferprocess.user=edc
    edc.datasource.transferprocess.password=<path:traceability-foss/data/dev/database#password>
    edc.hostname=consumer-controlplane.dev.demo.ftcpro.co
    edc.ids.catalog.id=urn:catalog:default
    edc.ids.description="Eclipse Dataspace Connector"
    edc.ids.endpoint=https://consumer-controlplane.dev.demo.ftcpro.co/BPNL00000003CML1/api/v1/ids
    ids.webhook.address=https://consumer-controlplane.dev.demo.ftcpro.co
    edc.ids.id=urn:connector:edc
    edc.ids.security.profile=base
    edc.ids.title="Eclipse Dataspace Connector"
    edc.receiver.http.endpoint=http://trace-api-wrapper:9192/callback/endpoint-data-reference
    edc.transfer.proxy.endpoint=https://consumer-dataplane.dev.demo.ftcpro.co/api/public
    edc.transfer.proxy.token.verifier.publickey.alias=daps-public-cert2
    edc.transfer.proxy.token.signer.privatekey.alias=daps-key2
    edc.vault.hashicorp.url=https://vault.dev.ftcpro.co/v1/
    edc.vault.hashicorp.health.check.enabled=false
    edc.vault.hashicorp.health.check.standby.ok=false
    edc.vault.hashicorp.api.secret.path=/traceability-foss
    edc.oauth.public.key.alias=daps-public-cert2
    edc.oauth.private.key.alias=daps-key2
    edc.oauth.client.id=A9:53:7B:46:BA:40:3C:10:1D:01:AB:0C:65:94:23:CA:E1:BF:86:8B:keyid:A9:53:7B:46:BA:40:3C:10:1D:01:AB:0C:65:94:23:CA:E1:BF:86:8B
    edc.oauth.provider.audience=idsc:IDS_CONNECTORS_ALL
    edc.oauth.provider.jwks.url=https://daps.dev.demo.ftcpro.co/.well-known/jwks.json
    edc.oauth.token.url=https://daps.dev.demo.ftcpro.co/token
    edc.vault.hashicorp.token=<path:traceability-foss/data/dev/edc#edc.vault.hashicorp.token>
    edc.data.encryption.keys.alias=daps-encryption-key
    edc.data.encryption.algorithm=AES
    edc.dataplane.selector.dataplane.url=http://localhost:9194/api/controlplane/control/transfer
    edc.dataplane.selector.dataplane.sourcetypes=HttpData,HttpProvision
    edc.dataplane.selector.dataplane.destinationtypes=HttpData,HttpProvision,HttpProxy
    edc.dataplane.selector.dataplane.properties={"publicApiUrl":"http://localhost:9196/api/public/","method":"POST"}
    edc.ids.endpoint.audience=https://trace-consumer-controlplane.dev.demo.ftcpro.co/BPNL00000003CML1/api/v1/ids/data


opentelemetry:
  # -- opentelemetry.properties configuring the [opentelemetry agent](https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/)
  properties: |-
    otel.javaagent.enabled=false
    otel.javaagent.debug=false